name: Build All GKI
on:
  push:
    paths:
      - 'lib/**'
      - 'src/**'
      - 'User/**'
      - 'Makefile'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build-matrix:
    strategy:
      matrix:
        kmi:
          - android12-5.10
          - android13-5.10
          - android13-5.15
          - android14-5.15
          - android14-6.1
          - android15-6.6
          - android16-6.12
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ylarod/ddk-min:${{ matrix.kmi }}-20260313
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: Fetch deps
        run: |
          git clone --depth 1 https://github.com/Dere3046/KernCall.git deps/Kerncall
          git -C deps/Kerncall checkout 0e19f97
          git clone --depth 1 https://github.com/Dere3046/Hidemod.git deps/hidemod
          git -C deps/hidemod checkout 0791574
          git clone --depth 1 https://github.com/Dere3046/Type_info.git deps/type_info
          git -C deps/type_info checkout aa514a6
          git clone --depth 1 https://github.com/Dere3046/KallRecon.git deps/type_info/kallrecon
          git -C deps/type_info/kallrecon checkout 8d647f0
      - name: Build
        run: make
      - uses: actions/upload-artifact@v4
        with:
          name: rwmem-${{ matrix.kmi }}
          path: rwmem.ko
